beauty_city/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('service.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path

from .auth_tools import set_passcode, verify_user, logout_user
from .views import service_page, index_page, note_page, servicefinally_page, \
    get_masters, get_services, get_categories, get_salons, profile_page, \
    get_order, get_payment, create_order, success, cancel, encode_username

app_name = "service"

urlpatterns = [
    path('service/', service_page, name="service_page"),
    path('', index_page, name="index_page"),
    path('set_passcode/', set_passcode, name="set_passcode"),
    path('verify_user/', verify_user, name="verify_user"),
    path('logout_user/', logout_user, name="logout_user"),
    path('note/', note_page, name="note_page"),
    path('servicefinally/', servicefinally_page, name="servicefinally_page"),
    path('choose_salons/', get_salons, name="choose_salons"),
    path('choose_categories/', get_categories, name="choose_categories"),
    path('choose_services/', get_services, name="choose_services"),
    path('choose_masters/', get_masters, name="choose_masters"),
    path('profile/', profile_page, name="profile_page"),
    path('get_order/', get_order, name="get_order"),
    path('get_payment/', get_payment, name="get_payment"),
    path('create_order/', create_order, name="create_order"),
    path('success/', success, name="success"),
    path('cancel/', cancel, name="cancel"),
    path('username/<str:username>/', encode_username, name="username"),
]

service/forms.py
from django import forms
from django.core.files.images import get_image_dimensions

from .models import User


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'second_name', 'image']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        # adding css classes to widgets without define the fields:
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

    def clean_avatar(self):
        image = self.cleaned_data['image']

        try:
            w, h = get_image_dimensions(image)

            # validate dimensions
            max_width = max_height = 400
            if w > max_width or h > max_height:
                raise forms.ValidationError(
                    u'Please use an image that is '
                    '%s x %s pixels or smaller.' % (max_width, max_height))

            # validate content type
            main, sub = image.content_type.split('/')
            if not (main == 'image' and sub in ['jpeg', 'pjpeg', 'gif',
                                                'png']):
                raise forms.ValidationError(u'Please use a JPEG, '
                                            'GIF or PNG image.')

            # validate file size
            if len(image) > (20 * 1024):
                raise forms.ValidationError(
                    u'Avatar file size may not exceed 20k.')

        except AttributeError:
            """
            Handles case when we are updating the user profile
            and do not supply a new avatar
            """
            pass

        return image

service/views.py
import datetime
import json

import stripe
from django.conf import settings
from django.core import serializers
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.decorators.csrf import csrf_exempt

from .auth_tools import get_user
from .forms import UserProfileForm
from .models import Salon, ServiceCategory, Master, Timeslot, Service, \
    Document, Comment, Order, User
from .serializers import CategorySerializer

stripe.api_key = settings.STRIPE_SECRET_KEY


def service_page(request):
    user = get_user(request)
    salons = Salon.objects.all()
    categories = ServiceCategory.objects.prefetch_related('services')
    masters = Master.objects.all()
    privacy_file = get_object_or_404(Document, title='privacy_polite')
    if user:
        client_info = {
            'first_name': user.first_name,
            'second_name': user.second_name,
            'image': request.build_absolute_uri(user.image.url)
        }
    else:
        client_info = {
            'first_name': 'undefined',
            'second_name': 'username',
            'image': None
        }
    context = {
        'client_info': client_info,
        'salons': [
            {
                'title': salon.title,
                'address': salon.address,
                'image': request.build_absolute_uri(salon.image.url),
                'id': salon.id
            }
            for salon in salons],
        'categories': [
            {
                'title': category.title,
                'services': category.services.all,
                'id': category.id,
            }
            for category in categories],
        'masters': [
            {
                'first_name': master.first_name,
                'second_name': master.second_name,
                'image': request.build_absolute_uri(master.image.url),
                'id': master.id

            }
            for master in masters],
        'client': user,
        'privacy_file': privacy_file,
    }

    return render(request, 'service.html', context)


def index_page(request):
    user = get_user(request)
    privacy_file = get_object_or_404(Document, title='privacy_polite')
    services = Service.objects.all()
    salons = Salon.objects.all()
    masters = Master.objects.all()
    comments = Comment.objects.all()

    if user:
        client_info = {
            'first_name': user.first_name,
            'second_name': user.second_name,
            'image': user.image.url
        }
    else:
        client_info = {
            'first_name': 'undefined',
            'second_name': 'username',
            'image': None
        }

    context = {
        'client_info': client_info,
        'privacy_file': privacy_file,
        'client': user,
        'services': [
            {
                'title': service.title,
                'price': service.price,
                'image': request.build_absolute_uri(service.image.url),
            }
            for service in services],

        'salons': [
            {
                'title': salon.title,
                'address': salon.address,
                'image': request.build_absolute_uri(salon.image.url),
            }
            for salon in salons],

        'masters': [
            {
                'first_name': master.first_name,
                'second_name': master.second_name,
                'salons': [master.title for master in master.salon.all()],
                'services': [master.title for master in master.service.all()],
                'image': request.build_absolute_uri(
                    master.image.url),
                'comments': comments.filter(master=master.id).count(),
            }
            for master in masters],

        'comments': [
            {
                'user_first_name': comment.user.first_name,
                'user_second_name': comment.user.second_name,
                'text': comment.text,
                'master': comment.master,
            }
            for comment in comments],
    }
    return render(request, 'index.html', context)


@csrf_exempt
def servicefinally_page(request):
    user = get_user(request)

    response = request.POST

    day, month, year = [int(date) for date in response['day'].split('.')]

    timeslot = Timeslot.objects.create(
        master=Master.objects.get(id=int(response['master'])),
        service=Service.objects.get(id=int(response['service'])),
        salon=Salon.objects.get(id=int(response['salon'])),
        day=datetime.date(year, month, day),
        time=response['time']
    )
    context = {
        'client': user,
        'client_info':
            {
                'first_name': user.first_name if user else None,
                'second_name': user.second_name if user else None,
                'image': user.image.url if user else None
            },
        'timeslot':
            {
                'id': timeslot.id,
                'master_first_name': timeslot.master.first_name,
                'master_second_name': timeslot.master.second_name,
                'master_image': request.build_absolute_uri(
                    timeslot.master.image.url),
                'salon': timeslot.salon.title,
                'salon_address': timeslot.salon.address,
                'service_title': timeslot.service.title,
                'service_price': timeslot.service.price,
                'day': timeslot.day,
                'time': timeslot.time
            },

    }

    return render(request, 'serviceFinally.html', context=context)


def get_order_date(orders_params):
    return orders_params['day']


def note_page(request):
    user = get_user(request)
    if not user:
        return redirect('service:index_page')
    orders = Order.objects.filter(client=user.id).prefetch_related(
        'master').prefetch_related('service').prefetch_related('salon')
    orders_params = []
    order_sum = 0
    orders_for_pay = []
    for order in orders:
        if order.day >= datetime.date.today():
            order_item = {
                'id': order.id,
                'master_first_name': order.master.first_name,
                'master_second_name': order.master.second_name,
                'master_image': request.build_absolute_uri(
                    order.master.image.url),
                'salon': order.salon.title,
                'salon_address': order.salon.address,
                'service_title': order.service.title,
                'service_price': order.service.price,
                'day': order.day,
                'time': order.time,
                'payment': order.payment,
                'created_at': order.created_at,
                'new': True
            }
            orders_params.append(order_item)
            if not order.payment:
                order_sum += order.service.price
                orders_for_pay.append(order.id)
        else:
            order_item = {
                'id': order.id,
                'master_first_name': order.master.first_name,
                'master_second_name': order.master.second_name,
                'master_image': request.build_absolute_uri(
                    order.master.image.url),
                'salon': order.salon.title,
                'salon_address': order.salon.address,
                'service_title': order.service.title,
                'service_price': order.service.price,
                'day': order.day,
                'time': order.time,
                'payment': order.payment,
                'created_at': order.created_at,
                'new': False
            }
            orders_params.append(order_item)

    orders_params_sorted = sorted(orders_params,
                                  key=get_order_date)
    context = {
        'client_info': {
            'first_name': user.first_name,
            'second_name': user.second_name,
            'image': request.build_absolute_uri(user.image.url)
        },
        'orders': orders_params_sorted,
        'order_sum': order_sum,
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY,
        'orders_for_pay': orders_for_pay,
    }
    return render(request, 'notes.html', context)


def get_salons(request):
    salons = Salon.objects.all()
    data = serializers.serialize('json', salons)
    return HttpResponse(data, content_type='application/json')


def get_categories(request):
    categories = ServiceCategory.objects.all().prefetch_related('services')
    if 'salon' in request.GET.keys():
        salon_title = request.GET['salon']
        salon = Salon.objects.filter(
            title=salon_title).first()
        if salon:
            categories = salon.categories.all().prefetch_related('services')

    serializer = CategorySerializer(categories, many=True)
    return JsonResponse(serializer.data, safe=False,
                        content_type='application/json')


def get_services(request):
    services = Service.objects.all()
    if 'salon' in request.GET.keys():
        salon = request.GET['salon']
        categories = Salon.objects.filter(title=salon).first().categories.all()
        services = services.filter(category__in=categories)
    if 'category' in request.GET.keys():
        category = request.GET['category']
        services = services.filter(category__title=category)
    data = serializers.serialize('json', services)
    return HttpResponse(data, content_type='application/json')


def get_masters(request):
    masters = Master.objects.all()
    if 'salon' in request.GET.keys():
        salon = request.GET['salon']
        masters = masters.filter(salon__title=salon)
    if 'service' in request.GET.keys():
        service_title = request.GET['service']
        service = Service.objects.filter(title=service_title).first()
        masters_id = service.masters.values_list('id',
                                                 flat=True) if service else []

templates/cancel.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Cancel</title>
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/air-datepicker.css' %}">
	<link rel="stylesheet" href="{% static 'css/jquery.arcticmodal-0.3.css' %}">
	<link rel="stylesheet" href="{% static 'css/simple.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<header id="header">
		<div class="container">
			<div class="header">
				<div class="row">
					<div class="col-2 col-md-2 mob">
						<img src="{% static 'img/hamburger.svg' %}" alt="hamburger" class="header__mobMenu">
					</div>
					<div class="col-5 col-md-3 col-lg-2">
						<a href="/">
							<img src="{% static 'img/Logo.svg' %}" alt="Logo" class="logo header__logo">
						</a>
					</div>
					<div class="col-md-5 ">
						<nav>
						<ul class="menu">
							<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
							<li class="menu__item"><a href="../service" class="menu__item_link">Услуги</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
							<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
						</ul>
					</nav>
					</div>
					<div class="col-3 col-md-2 col-lg-3">
						<div class="header__block">
						<a href="tel:+79179023800"><button class="header__block_btn">Перезвоните мне</button></a>
							<div class="header__block_auth">
								<img src="{{client_info.image}}" alt="account" class="header__account_img">
								<span class="header__block_auth__intro">
									{{client_info.first_name}} {{client_info.second_name}}</span>
							</div>
							<span class="menu__item_link" style="margin-left: 50px"></span>
							<a href="{% url 'service:logout_user' %}" class="menu__item_link">Выйти</a>
					</div>
					</div>
				</div>



			</div>
		</div>
	</header>
<div class="container">
<div class="alert alert-primary" role="alert">
    <section>
    <p>Something went wrong ...</p>
</section>
</div>
</div>


<footer id="footer">
		<div class="container">
			<div class="footer">
				<div class="footer__block">
					<div class="row">
						<div class="col-md-3 col-lg-2">
							<a href="/"><img src="{% static 'img/Logo.svg' %}" alt="logo" class="footer__logo"></a>
						</div>
						<div class="col-md-5 minMobHide">
							<nav>
								<ul class="menu">
									<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
									<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
								</ul>
							</nav>
						</div>
					</div>
					<div class="footer__contact">
						<div class="row">
							<div class="col-md-4">

									<div class="footer__data">с 10:00 до 20:00  без выходных</div>

							</div>
							<div class="col-md-3">
								<a href="tel:+79179023800" class="contacts__info_tel">+7 (917) 902 38 00</a>
							</div>
						</div>
						<div class="row">
							<div class="col-md-5 minMobShow">
								<nav>
									<ul class="menu">
										<li class="menu__item"><a href="#" class="menu__item_link">Мастера</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Услуги</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Отзывы</a></li>
										<li class="menu__item"><a href="#" class="menu__item_link">Контакты</a></li>
									</ul>
								</nav>
							</div>
						</div>
					</div>
					<hr class="hr"></hr>
					<div class="footer__bottom">
						<div class="row">
							<div class="col-md-4 col-lg-3">
								<a href="#" class="footer__link">Политика конфиденциальности</a>
							</div>
							<div class="col-md-3">
								<div class="footer__copy">2022. Все права защищены</div>
							</div>
							<div class="col-md-3 col-lg-2">
								<div class="footer__social fic">
									<a href=""><img src="{% static 'img/waGray.svg' %}" alt="wa" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/vkGray.svg' %}" alt="vk" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/tgGray.svg' %}" alt="tg" class="contacts__social_icon"></a>
									<a href=""><img src="{% static 'img/instaGray.svg' %}" alt="insta" class="contacts__social_icon"></a>
								</div>
							</div>
						</div>



					</div>

				</div>
			</div>
		</div>
	</footer>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" integrity="sha512-XtmMtDEcNz2j7ekrtHvOVR4iwwaD6o/FUJe6+Zq+HgcCsk3kj4uSQQR8weQ2QVj1o0Pk6PwYLohm206ZzNfubg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="{% static 'js/air-datepicker.js' %}"></script>
	<script src="{% static 'js/jquery.arcticmodal-0.3.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/popup.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
	<link rel="stylesheet" href="css/main.css">
</head>
<body>
	<div class="authPopup popup">
		<div class="popup__title authPopup__title">Войти по коду</div>
		<p class="popup__text authPopup__text">Введите свой номер телефона, мы вышлем на него код</p>
		<form action="#" class="authPopup__form">
			<div class="contacts__form_inputBlock">
				<input type="text" name="tel" class="contacts__form_iunput" placeholder="+7(999)999--99-99" required="">
			</div>
			<div class="contacts__form_checkboxBlock fic">
				<input type="checkbox" class="contacts__form_checkbox" checked="">
				<span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
			</div>
			<button type="submit" class="popup__btn authPopup__btn">Отправить</button>
		</form>
	</div>

	<div class="confirmPopup popup">
		<div class="popup__title confirmPopup__title">Подтвердите номер</div>
		<p class="popup__text confirmPopup__text">Введите код, полученный по SMS на номер +7 (928) 164 48 60</p>
		<div class="confirmPopup__number">
			<input type="text" name="num1" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num2" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num3" class="tipsPopup__form_inputNum popup__input" placeholder="" required>
			<input type="text" name="num4" class="tipsPopup__form_inputNum popup__input" placeholder="" required>

		</div>
		<div class="confirmPopup__sms">Если SMS не пришло вы можете <a href="#" class="popup__link">запросить код повторно</a></div>
		<div class="confirmPopup__changeNumber">
			<a href="#" class="confirmPopup__link popup__link">Изменить номер телефона</a>
		</div>
	</div>

	<div class="tipsPopup popup">
		<div class="popup__title tipsPopup__title">Чаевые</div>
		<form action="#" class="tipsPopup__form">
			<div class="tipsPopup__form_intro popup__intro">Введите сумму чаевых</div>
			<input type="text" class="tipsPopup__form_input popup__input" placeholder="0.00" required>
			<button class="tipsPopup__btn popup__btn">Далее</button>
		</form>
	</div>

	<div class="paymentPopup popup">
		<div class="popup__title paymentPopup__title">Оплата</div>
		<form action="#" class="paymentPopup__form">
			<div class="paymentPopup__form_intro popup__intro">номер карты</div>
			<input type="text" name="tel" class="paymentPopup__form_input popup__input" placeholder="Введите номер" required>
			<div class="paymentPopup__form_block fic">
				<input type="text" name="mm" class="tipsPopup__form_inputMin popup__input" placeholder="ММ" required>
				<input type="text" name="gg" class="tipsPopup__form_inputMin popup__input" placeholder="ГГ" required>
			</div>
			<div class="paymentPopup__form_elems fic">
				<input type="text" name="fname" class="paymentPopup__form_inputMid popup__input" placeholder="Имя владельца" required>
				<input type="text" name="cvc" class="tipsPopup__form_inputMin popup__input" placeholder="CVC" required>
			</div>
			<div class="paymentPopup__form_intro popup__intro">Ваш e-mail(необязательно)</div>
			<input type="email" name="tel" class="paymentPopup__form_input popup__input" placeholder="pochta@mail.ru">
			<button class="tipsPopup__btn popup__btn">Оплатить</button>
		</form>
	</div>

	<div class="reviewPopup popup">
		<div class="popup__title reviewPopup__title">Отзыв</div>
		<form action="#" class="reviewPopup__form">
			<input type="text" name="fname" class="paymentPopup__form_input popup__input" placeholder="Введите имя" required>
			<div class="contacts__form_inputBlock">
				<input type="text" name="tel" class="contacts__form_iunput" placeholder="+7(999)999--99-99" required="">
			</div>
			<input type="text" name="dateVis" class="paymentPopup__form_input popup__input" placeholder="Дата посещения" required>
			<textarea name="popupTextarea" class="reviewPopup__form_textarea" placeholder="Текст отзыва"></textarea>
			<div class="contacts__form_checkboxBlock fic">
				<input type="checkbox" class="contacts__form_checkbox" checked>
				<span class="contacts__form_checkboxBlock__intro">Я согласен(а) с политикой конфидециоальности</span>
			</div>
			<button class="tipsPopup__btn popup__btn">Оплатить</button>
		</form>
	</div>
</body>
</html>

templates/stripe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stripe Redirect</title>
    <script src="https://js.stripe.com/v3/"></script>

</head>
<body>

<script>
var stripe = Stripe('{{ stripe_public_key }}');
stripe.redirectToCheckout({ sessionId: '{{session_id}}' })
</script>

</body>
</html>